### ISSUE TITLE
Front-end accessible customerId/supplierId <-> tenantId converter

### ISSUE THREAD

**Issue by kekonen** [OpusCapita/useridentity-middleware#10]
Related: https://github.com/OpusCapita/onboarding/issues/498
Right now there is now easy access to methods like `getTenantId` / `customerIdToTenantId` / `supplierIdToTenantId`, in order to utilize them in the UI. 
it is needed to develop an easier way to access functionality of this utility from UI. 
One of the possible approaches can be an introduction of the utility to Context.

**Comment by nczeranka** [comment]
see bouncer -> e.g.: this.context.bouncer.getUserTenants()
