### ISSUE TITLE
Adjust README.md

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/useridentity-middleware#8]
Please add more detailed info how to configure/use useridentity-middleware. Now there is only one way to understand how does it work - go into the _bnp_ and look through the source code.

P.S.
Fix the existing docs 
change `req.userData` - > `req.opuscapita.userData()`

**Comment by kwierchris** [comment]
Please make the documentation a bit more specific and update it so people know from it which data is available and how it is accessed.

**Comment by kwierchris** [comment]
Done.
