### ISSUE TITLE
Allow injecting user claims via cookie in NODE_ENV=development

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/useridentity-middleware#9]
On prod we can support signed JWT only,
but on dev it is overhead to have every project add kong, auth, user, acl to docker-compose

To simplify, we need to enhance nginx-rp image to work as reverse proxy with cookie injection.

User claims cookie can be OC_USER_CLAIMS {simple json claims structure}
so that from service point of view, behaviour is same as if we had proper ID Token

**Comment by sureshvarman-cronj** [comment]
Fixed in https://github.com/OpusCapita/nginx-rp/tree/develop
